import "./globals.css";

import { DM_Sans } from "next/font/google";

import Providers from "@/app/providers";
// import { Header } from "@/components/layout/header";
import { getSession } from "@/lib/auth";
import { cn } from "@/lib/utils";

import type { Metadata } from "next";

const fontSans = DM_Sans({ subsets: ["latin"], variable: "--font-sans" });

const fontHeading = DM_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </head>
      <body className={cn("font-sans antialiased", fontSans.variable, fontHeading.variable)}>
        <Providers session={session}>
          <main className="container flex h-screen py-10">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
